# LSTM to Identify Stress Partens

## Importing Data

* TEMP.csv: 
Data from temperature sensor expressed degrees on the Celsius (°C) scale.

* EDA.csv:
Data from the electrodermal activity sensor expressed as microsiemens (μS).

* BVP.csv:
Data from photoplethysmograph.

* ACC.csv:
Data from 3-axis accelerometer sensor. The accelerometer is configured to measure acceleration in the range [-2g, 2g]. Therefore the unit in this file is 1/64g.
Data from x, y, and z axis are respectively in first, second, and third column.

* IBI.csv:
Time between individuals heart beats extracted from the BVP signal.
No sample rate is needed for this file.
The first column is the time (respect to the initial time) of the detected inter-beat interval expressed in seconds (s).
The second column is the duration in seconds (s) of the detected inter-beat interval (i.e., the distance in seconds from the previous beat).

* HR.csv:
Average heart rate extracted from the BVP signal.The first row is the initial time of the session expressed as unix timestamp in UTC.
The second row is the sample rate expressed in Hz.


* tags.csv:
Event mark times.
Each row corresponds to a physical button press on the device; the same time as the status LED is first illuminated.
The time is expressed as a unix timestamp in UTC and it is synchronized with initial time of the session indicated in the related data files from the corresponding session.

In [100]:
import pandas as pd
import numpy as np
import os
from zipfile import ZipFile

In [46]:
root_path = "//Users/i546644/Documents/Unisinos/WESAD"

In [164]:
subjects_available = os.listdir(root_path)

In [166]:
subjects_available

['S5',
 'S2',
 'S3',
 'S4',
 '.DS_Store',
 'S17',
 'S10',
 'S11',
 'S16',
 'S8',
 'S6',
 'S7',
 'S9',
 'S13',
 'S14',
 'S15',
 'wesad_readme.pdf']

In [167]:
subjects_available.remove(".DS_Store")
subjects_available.remove("wesad_readme.pdf")

In [168]:
subjects_available

['S5',
 'S2',
 'S3',
 'S4',
 'S17',
 'S10',
 'S11',
 'S16',
 'S8',
 'S6',
 'S7',
 'S9',
 'S13',
 'S14',
 'S15']

In [177]:
data_names = [
    "TEMP",
    "EDA",
    "BVP",
    "ACC",
    "IBI",
    "HR",
    "TAGS"
]

In [51]:
zip_label = "_E4_Data.zip"
label = "_E4_Data"

In [171]:
def unzip_files():
    
    subjects_data_paths = []
    
    for subject in subjects_available:
        # extracting data from zip files
        subject_E4_data_path = os.path.join(root_path, subject, subject + label)
        subject_zip_data_path = os.path.join(root_path, subject, subject + zip_label)
        subjects_data_paths.append(subject_E4_data_path)
        with ZipFile(subject_zip_data_path, 'r') as zipObj:
            zipObj.extractall(subject_E4_data_path)
    
    return subjects_data_paths

In [173]:
unzip_files()

['//Users/i546644/Documents/Unisinos/WESAD/S5/S5_E4_Data',
 '//Users/i546644/Documents/Unisinos/WESAD/S2/S2_E4_Data',
 '//Users/i546644/Documents/Unisinos/WESAD/S3/S3_E4_Data',
 '//Users/i546644/Documents/Unisinos/WESAD/S4/S4_E4_Data',
 '//Users/i546644/Documents/Unisinos/WESAD/S17/S17_E4_Data',
 '//Users/i546644/Documents/Unisinos/WESAD/S10/S10_E4_Data',
 '//Users/i546644/Documents/Unisinos/WESAD/S11/S11_E4_Data',
 '//Users/i546644/Documents/Unisinos/WESAD/S16/S16_E4_Data',
 '//Users/i546644/Documents/Unisinos/WESAD/S8/S8_E4_Data',
 '//Users/i546644/Documents/Unisinos/WESAD/S6/S6_E4_Data',
 '//Users/i546644/Documents/Unisinos/WESAD/S7/S7_E4_Data',
 '//Users/i546644/Documents/Unisinos/WESAD/S9/S9_E4_Data',
 '//Users/i546644/Documents/Unisinos/WESAD/S13/S13_E4_Data',
 '//Users/i546644/Documents/Unisinos/WESAD/S14/S14_E4_Data',
 '//Users/i546644/Documents/Unisinos/WESAD/S15/S15_E4_Data']

### 1) Try to create all data in a DataFrame

In [182]:
def create_df(subjects, data_name):
    
    all_dfs = []
    
    data_name = data_name.upper()
    
    for subject in subjects:
        file_path = os.path.join(root_path, subject, subject + label, data_name + ".csv")
        df = pd.read_csv(file_path, names = [data_name])
        df["SUBJECT"] = subject
        all_dfs.append(df)
        
    return pd.concat(all_dfs)

In [183]:
def create_all_data(data_names, subjects):
    
    all_data = {}
    
    for data in data_names:
        all_data[data] = create_df(subjects=subjects, data_name=data)
        
    return all_data

In [184]:
all_data = create_all_data(data_names, subjects_available)

In [185]:
all_data

{'TEMP':                TEMP SUBJECT
 0      1.497357e+09      S5
 1      4.000000e+00      S5
 2      3.822100e+02      S5
 3      3.822100e+02      S5
 4      3.822100e+02      S5
 ...             ...     ...
 26565  2.895000e+01     S15
 26566  2.897000e+01     S15
 26567  2.897000e+01     S15
 26568  2.897000e+01     S15
 26569  2.897000e+01     S15
 
 [427766 rows x 2 columns],
 'EDA':                 EDA SUBJECT
 0      1.497357e+09      S5
 1      4.000000e+00      S5
 2      0.000000e+00      S5
 3      4.003090e-01      S5
 4      4.757670e-01      S5
 ...             ...     ...
 26565  5.298760e-01     S15
 26566  5.106880e-01     S15
 26567  5.349930e-01     S15
 26568  5.592990e-01     S15
 26569  5.720920e-01     S15
 
 [427794 rows x 2 columns],
 'BVP':                  BVP SUBJECT
 0       1.497357e+09      S5
 1       6.400000e+01      S5
 2      -0.000000e+00      S5
 3      -0.000000e+00      S5
 4      -0.000000e+00      S5
 ...              ...     ...
 425136  2.2

### 2) Try to create all datra in lists

In [91]:
temp_list = []
eda_list = []
bvp_list = []
acc_list = []
ibi_list = []
hr_list = []
tags_list = []

for subject in available_data:
    # extracting data from zip files
    subject_E4_data_path = os.path.join(root_path, subject, subject + label)
    subject_zip_data_path = os.path.join(root_path, subject, subject + zip_label)
    with ZipFile(subject_zip_data_path, 'r') as zipObj:
        zipObj.extractall(subject_E4_data_path)
        
    # creating data file
    
    # TEMP files
    subject_temp_path = os.path.join(subject_E4_data_path, "TEMP.csv")
    subject_temp_data = np.genfromtxt(subject_temp_path, delimiter=",")
    temp_list.append(subject_temp_data)
    
    # EDA files
    subject_eda_path = os.path.join(subject_E4_data_path, "EDA.csv")
    subject_eda_data = np.genfromtxt(subject_eda_path, delimiter=",")
    eda_list.append(subject_eda_data)
    
    # BVP files
    subject_bvp_path = os.path.join(subject_E4_data_path, "BVP.csv")
    subject_bvp_data = np.genfromtxt(subject_bvp_path, delimiter=",")
    bvp_list.append(subject_bvp_data)
    
    # ACC files
    subject_acc_path = os.path.join(subject_E4_data_path, "ACC.csv")
    subject_acc_data = np.genfromtxt(subject_acc_path, delimiter=",")
    acc_list.append(subject_acc_data)
    
    # IBI files
    subject_ibi_path = os.path.join(subject_E4_data_path, "IBI.csv")
    subject_ibi_data = np.genfromtxt(subject_ibi_path, delimiter=",")
    ibi_list.append(subject_ibi_data)
    
    # HR files
    subject_hr_path = os.path.join(subject_E4_data_path, "HR.csv")
    subject_hr_data = np.genfromtxt(subject_hr_path, delimiter=",")
    hr_list.append(subject_hr_data)
    
    # TAGS files
    subject_tags_path = os.path.join(subject_E4_data_path, "TAGS.csv")
    subject_tags_data = np.genfromtxt(subject_tags_path, delimiter=",")
    tags_list.append(subject_tags_data)

<ipython-input-91-026c342373ab>:50: UserWarning: genfromtxt: Empty input file: "//Users/i546644/Documents/Unisinos/WESAD/S2/S2_E4_Data/TAGS.csv"
  subject_tags_data = np.genfromtxt(subject_tags_path, delimiter=",")
<ipython-input-91-026c342373ab>:50: UserWarning: genfromtxt: Empty input file: "//Users/i546644/Documents/Unisinos/WESAD/S3/S3_E4_Data/TAGS.csv"
  subject_tags_data = np.genfromtxt(subject_tags_path, delimiter=",")


In [ ]:
for subject in available_data:
    # extracting data from zip files
    subject_E4_data_path = os.path.join(root_path, subject, subject + label)
    subject_zip_data_path = os.path.join(root_path, subject, subject + zip_label)
    with ZipFile(subject_zip_data_path, 'r') as zipObj:
        zipObj.extractall(subject_E4_data_path)
        
    # creating data file
    
    # TEMP files
    subject_temp_path = os.path.join(subject_E4_data_path, "TEMP.csv")
    subject_temp_data = np.genfromtxt(subject_temp_path, delimiter=",")
    temp_list.append(subject_temp_data)
    
    # EDA files
    subject_eda_path = os.path.join(subject_E4_data_path, "EDA.csv")
    subject_eda_data = np.genfromtxt(subject_eda_path, delimiter=",")
    eda_list.append(subject_eda_data)
    
    # BVP files
    subject_bvp_path = os.path.join(subject_E4_data_path, "BVP.csv")
    subject_bvp_data = np.genfromtxt(subject_bvp_path, delimiter=",")
    bvp_list.append(subject_bvp_data)
    
    # ACC files
    subject_acc_path = os.path.join(subject_E4_data_path, "ACC.csv")
    subject_acc_data = np.genfromtxt(subject_acc_path, delimiter=",")
    acc_list.append(subject_acc_data)
    
    # IBI files
    subject_ibi_path = os.path.join(subject_E4_data_path, "IBI.csv")
    subject_ibi_data = np.genfromtxt(subject_ibi_path, delimiter=",")
    ibi_list.append(subject_ibi_data)
    
    # HR files
    subject_hr_path = os.path.join(subject_E4_data_path, "HR.csv")
    subject_hr_data = np.genfromtxt(subject_hr_path, delimiter=",")
    hr_list.append(subject_hr_data)
    
    # TAGS files
    subject_tags_path = os.path.join(subject_E4_data_path, "TAGS.csv")
    subject_tags_data = np.genfromtxt(subject_tags_path, delimiter=",")
    tags_list.append(subject_tags_data)

In [ ]:
def unzip_files():
    for subject in available_data:
    # extracting data from zip files
    subject_E4_data_path = os.path.join(root_path, subject, subject + label)
    subject_zip_data_path = os.path.join(root_path, subject, subject + zip_label)
    with ZipFile(subject_zip_data_path, 'r') as zipObj:
        zipObj.extractall(subject_E4_data_path)

In [ ]:
def get_single_df()

In [92]:
temp_list

[array([1.49735653e+09, 4.00000000e+00, 3.82210000e+02, ...,
        3.09300000e+01, 3.09300000e+01, 3.09300000e+01]),
 array([1.49543732e+09, 4.00000000e+00, 3.82180000e+02, ...,
        3.38100000e+01, 3.38100000e+01, 3.38100000e+01]),
 array([1.49562413e+09, 4.00000000e+00, 3.82180000e+02, ...,
        3.07300000e+01, 3.07300000e+01, 3.07300000e+01]),
 array([1.49734282e+09, 4.00000000e+00, 3.82210000e+02, ...,
        3.13500000e+01, 3.13500000e+01, 3.13500000e+01]),
 array([1.50243596e+09, 4.00000000e+00, 3.82210000e+02, ...,
        3.15700000e+01, 3.15700000e+01, 3.15700000e+01]),
 array([1.50096631e+09, 4.00000000e+00, 3.82210000e+02, ...,
        3.07900000e+01, 3.07900000e+01, 3.07900000e+01]),
 array([1.50098126e+09, 4.00000000e+00, 3.82210000e+02, ...,
        3.15100000e+01, 3.15100000e+01, 3.15100000e+01]),
 array([1.50236636e+09, 4.00000000e+00, 3.82210000e+02, ...,
        2.94900000e+01, 2.94900000e+01, 2.94900000e+01]),
 array([1.49968504e+09, 4.00000000e+00, 3.822100

In [93]:
eda_list

[array([1.49735653e+09, 4.00000000e+00, 0.00000000e+00, ...,
        1.27800000e+00, 1.26904800e+00, 1.26393200e+00]),
 array([1.49543732e+09, 4.00000000e+00, 0.00000000e+00, ...,
        3.89792000e-01, 3.87229000e-01, 4.15418000e-01]),
 array([1.49562413e+09, 4.00000000e+00, 0.00000000e+00, ...,
        3.12893000e-01, 3.12893000e-01, 3.12893000e-01]),
 array([1.49734282e+09, 4.00000000e+00, 0.00000000e+00, ...,
        1.92143000e-01, 1.89584000e-01, 1.90863000e-01]),
 array([1.50243596e+09, 4.00000000e+00, 0.00000000e+00, ...,
        1.56278700e+00, 1.70096300e+00, 1.74830100e+00]),
 array([1.50096631e+09, 4.00000000e+00, 0.00000000e+00, ...,
        1.03135000e+00, 1.02495400e+00, 1.03007100e+00]),
 array([1.50098126e+09, 4.00000000e+00, 0.00000000e+00, ...,
        2.51000400e+00, 2.55349900e+00, 2.54198600e+00]),
 array([1.50236636e+09, 4.00000000e+00, 0.00000000e+00, ...,
        4.99234000e-01, 5.06911000e-01, 5.08190000e-01]),
 array([1.49968504e+09, 4.00000000e+00, 0.000000

In [94]:
bvp_list

[array([ 1.49735653e+09,  6.40000000e+01, -0.00000000e+00, ...,
        -9.28400000e+01, -1.16070000e+02, -1.30310000e+02]),
 array([ 1.49543732e+09,  6.40000000e+01, -0.00000000e+00, ...,
         8.56100000e+01,  7.59800000e+01,  6.58600000e+01]),
 array([ 1.49562413e+09,  6.40000000e+01, -0.00000000e+00, ...,
         7.00000000e+00,  6.08000000e+00,  5.50000000e+00]),
 array([ 1.49734282e+09,  6.40000000e+01, -0.00000000e+00, ...,
        -8.67500000e+01, -1.00390000e+02, -1.11340000e+02]),
 array([ 1.50243596e+09,  6.40000000e+01, -0.00000000e+00, ...,
        -5.22600000e+01, -5.21100000e+01, -5.22100000e+01]),
 array([ 1.50096631e+09,  6.40000000e+01, -0.00000000e+00, ...,
         2.17100000e+01,  2.21800000e+01,  2.26000000e+01]),
 array([ 1.50098126e+09,  6.40000000e+01, -0.00000000e+00, ...,
         1.82300000e+01,  2.06400000e+01,  2.22700000e+01]),
 array([ 1.50236636e+09,  6.40000000e+01, -0.00000000e+00, ...,
        -3.55300000e+01, -3.33500000e+01, -3.10400000e+01]),


In [95]:
acc_list

[array([[1.49735653e+09, 1.49735653e+09, 1.49735653e+09],
        [3.20000000e+01, 3.20000000e+01, 3.20000000e+01],
        [0.00000000e+00, 5.00000000e+00, 6.30000000e+01],
        ...,
        [0.00000000e+00, 6.00000000e+00, 6.20000000e+01],
        [0.00000000e+00, 6.00000000e+00, 6.30000000e+01],
        [0.00000000e+00, 6.00000000e+00, 6.40000000e+01]]),
 array([[ 1.49543732e+09,  1.49543732e+09,  1.49543732e+09],
        [ 3.20000000e+01,  3.20000000e+01,  3.20000000e+01],
        [ 2.90000000e+01, -6.00000000e+00,  5.50000000e+01],
        ...,
        [ 6.00000000e+01, -1.40000000e+01,  4.00000000e+00],
        [ 6.30000000e+01, -1.40000000e+01,  5.00000000e+00],
        [ 6.30000000e+01, -1.40000000e+01,  5.00000000e+00]]),
 array([[ 1.49562413e+09,  1.49562413e+09,  1.49562413e+09],
        [ 3.20000000e+01,  3.20000000e+01,  3.20000000e+01],
        [-2.70000000e+01,  4.00000000e+00,  5.70000000e+01],
        ...,
        [-2.60000000e+01,  5.70000000e+01,  1.60000000e+01],

In [96]:
ibi_list

[array([[1.49735653e+09,            nan],
        [1.26255780e+01, 9.37543000e-01],
        [1.34849920e+01, 8.59414000e-01],
        ...,
        [7.05674489e+03, 9.84420000e-01],
        [7.05782307e+03, 1.07817400e+00],
        [7.05890124e+03, 1.07817400e+00]]),
 array([[1.49543732e+09,            nan],
        [1.43131550e+01, 7.65660000e-01],
        [1.52038210e+01, 8.90666000e-01],
        ...,
        [7.85365637e+03, 9.84420000e-01],
        [7.85467204e+03, 1.01567100e+00],
        [7.85543770e+03, 7.65660000e-01]]),
 array([[1.49562413e+09,            nan],
        [1.06723640e+01, 9.53169000e-01],
        [1.94540150e+01, 9.84420000e-01],
        ...,
        [7.53875133e+03, 1.17192900e+00],
        [7.53993889e+03, 1.18755400e+00],
        [7.54120457e+03, 1.26568300e+00]]),
 array([[1.49734282e+09,            nan],
        [1.44537870e+01, 7.50034000e-01],
        [1.52975750e+01, 8.43789000e-01],
        ...,
        [7.84262462e+03, 1.03129700e+00],
        [7.8437184

In [97]:
hr_list

[array([1.49735654e+09, 1.00000000e+00, 6.00000000e+01, ...,
        7.85500000e+01, 7.83500000e+01, 7.81700000e+01]),
 array([1.49543734e+09, 1.00000000e+00, 1.01000000e+02, ...,
        8.26700000e+01, 8.33500000e+01, 8.40300000e+01]),
 array([1.49562414e+09, 1.00000000e+00, 1.24000000e+02, ...,
        7.03000000e+01, 7.02500000e+01, 7.01800000e+01]),
 array([1.49734283e+09, 1.00000000e+00, 8.50000000e+01, ...,
        1.04030000e+02, 1.03000000e+02, 1.01980000e+02]),
 array([1.50243597e+09, 1.00000000e+00, 6.00000000e+01, ...,
        7.43800000e+01, 7.40300000e+01, 7.36500000e+01]),
 array([1.50096632e+09, 1.00000000e+00, 7.10000000e+01, ...,
        8.04300000e+01, 8.07000000e+01, 8.09200000e+01]),
 array([1.50098127e+09, 1.00000000e+00, 8.20000000e+01, ...,
        8.08800000e+01, 8.09000000e+01, 8.09300000e+01]),
 array([1.50236638e+09, 1.00000000e+00, 5.80000000e+01, ...,
        8.24500000e+01, 8.24300000e+01, 8.24300000e+01]),
 array([1.49968505e+09, 1.00000000e+00, 1.000000

In [98]:
tags_list

[array(1.49736408e+09),
 array([], dtype=float64),
 array([], dtype=float64),
 array(1.49735082e+09),
 array(1.50244319e+09),
 array(1.50097313e+09),
 array(1.50098772e+09),
 array(1.50237347e+09),
 array(1.49969168e+09),
 array(1.49744756e+09),
 array(1.49934596e+09),
 array(1.49977767e+09),
 array(1.50219765e+09),
 array(1.50226956e+09),
 array(1.5023557e+09)]

## Creating Model

In [99]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence

In [ ]:
embedding_vecor_length = 32
model = Sequential()
model.add(Embedding(top_words, embedding_vecor_length, input_length=max_review_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())